### ISSUE TITLE
Some options should be adopted & discussed

### ISSUE THREAD

**Issue by zhongkai** [searchfe/tsconfig#2]
建议强制：`noFallthroughCasesInSwitch: true`，应该对 `switch-case` 强制禁止穿透限制。
需要讨论：`noEmitHelpers: true` 是否要引入，是否应该把 Helpers 提取出来，只做 `importHelpers: true` 无法解决不同编译产物一起使用时的冗余问题。

**Comment by xueran** [comment]
如线下讨论结论：
1.  `noFallthroughCasesInSwitch: true`
2. `noEmitHelpers: false`
